- name: Create users
  hosts: all
  remote_user: root
  tasks:
  - name: Create admin user
    ansible.builtin.user:
        name: admin
        group: sudo
        shell: /bin/bash
        password: '!'

  - name: Set ssh access
    ansible.builtin.authorized_key:
      user: admin
      state: present
      key: "{{ lookup('file', '~/.ssh/id_ed25519.pub')}}"
- name: Install packages
  hosts: myhosts
  remote_user: root
  tasks:
  - name: Install packages
    ansible.builtin.apt:
      name: nginx
      state: latest